Social media website - Milestone: friendships v1
Abhigyan001/ror-social-scaffold pull request #2
Opened 2020-11-11 10:48 UTC by Abhigyan001

In this milestone, we implemented the following features for a logged-in user :

A user is able to see all users list.
A user is able to send a friendship invitation.
A user can see a button “Send Invitation” next to the name of the user who is not his friend yet.
A user is able to see pending friendship invitations sent to him from other users.
A user is able to accept or reject friendships invitation.
A user is able to see his friends.

2020-11-11 11:51 UTC, Dandush03 requested changes
# Status: Require Changes :stop_sign: 

### Great Work So Far :muscle: 
**Please fix all the issues pointed below before submitting for a new review**
- [ ] **All User Tab:** Should not display current user
- [ ] **Post Friend and Logged User:** Posts timeline includes posts written by logged-in user and their friends
- [ ] **Tests:** Make sure you test each route/model/controller/view of the application
- [ ] **Inconsisty ruby version:** check my comments [here]()
- [ ] ** Database Configuration:** check my comments [here]()

# Happy Coding :nerd_face: :computer:

2020-11-11 11:51 UTC, Dandush03 commented on Gemfile
> +ruby '>=2.6.6'
- [ ] **Inconsisty ruby version:** your `Gemfile` and your `.ruby-version` have 2 different ruby version which course issues when running blunder, especially if the user has multiple environments

2020-11-11 11:51 UTC, Dandush03 commented on config/database.yml
> +  timeout: 5000
- [ ] **Database Configuration:** I got multiple errors while trying to migrate your database due to the fact that you've set most of the pg configuration for development. let's make it work in the test environment and the production environment
```yml
default: &default
  adapter: postgresql
  username: postgres
  password: 12345
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: ror_social_scaffold_development
```

2020-11-12 09:38 UTC, elmejdki requested changes
# status: require changes :recycle: 
## Hello guys :wave: :wave: :wave:, you still have some work :hammer: :toolbox: :wrench: to do, please make all the changes commented bellow.

- [ ] A  user should be able to reject a friend request:
![image](https://user-images.githubusercontent.com/34653764/98918268-b1834d80-24cd-11eb-8153-8542f55536e7.png)

- [ ] User should be able to see pending request:
![image](https://user-images.githubusercontent.com/34653764/98921986-34a6a280-24d2-11eb-9ce7-e75c48135bd1.png)

- [ ] A user should be able to accept or reject a request:
![image](https://user-images.githubusercontent.com/34653764/98922229-80594c00-24d2-11eb-8434-05ce597a23b0.png)

- [ ] show an add friend button on the user page:
![image](https://user-images.githubusercontent.com/34653764/98922309-9830d000-24d2-11eb-9ce6-199ca0caf1c1.png)

- [ ] As mentioned by the previous TSE:
![image](https://user-images.githubusercontent.com/34653764/98922474-c6161480-24d2-11eb-9f8e-c26af343b571.png)

- [ ] Add a linter to your project it's not configured yet.

### please make all the required changes before you submit another code review.
## Happy Coding :tophat:

2020-11-12 10:36 UTC, rOluochKe approved these changes
Hello Team
### Well done :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

2020-11-12 10:52 UTC, merged